### PR TITLE
add 10.0-1

### PR DESCRIPTION
**Pull request by mysticmind**

### CODE REVIEW

**Comment by mihasic** [comment]
@mysticmind, do you know how to download a 'portable' postgres 10 without registration on enterprisedb.com?

**Comment by mysticmind** [comment]
@mihasic Check http://www.enterprisedb.com/products-services-training/pgdownload, you should be able to download without registration

**Comment by mysticmind** [comment]
Are you looking to automate the process of creating the lite binary package?

**Comment by mihasic** [comment]
That would be ideal, but probably not worth it yet.
At this point I wanted to verify the download (with binaries I'm a bit paranoid).

And thank you for the pull request, I've just publish the packages (worked in my manual tests).

**Comment by mysticmind** [comment]
@mihasic I figured it out, use http://get.enterprisedb.com/postgresql/<zip file name>, ex. http://get.enterprisedb.com/postgresql/postgresql-9.5.9-1-windows-x64-binaries.zip

**Pull request merged**
